# Generated by Django 5.1 on 2024-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_profile_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experiences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
