# Generated by Django 5.1 on 2024-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
